/* One bilingual content source for the site and the approval documents. */
(() => {
  const b = (ar, en) => ({ar, en});
  window.SAMT_DATA = {
    version: '1.0', reviewed: '2026-09-25',
    nav: [
      ['home', b('المبادرة','The initiative')], ['programme', b('رحلة الإعداد','The programme')],
      ['proposal', b('ملف الاعتماد','Approval case')], ['demo', b('التجربة التفاعلية','Explore the platform')]
    ],
    domains: [
      {id:'strategy', name:b('التقدير الاستراتيجي','Strategic judgement'), weight:20, description:b('قراءة التحولات الجيوسياسية وربط الخيارات بالأولويات الوطنية والمؤسسية.','Interpret geopolitical change and connect choices to national and institutional priorities.'), evidence:b('موجز خيارات يوضح الافتراضات والمخاطر وآثار القرار.','An options brief stating assumptions, risks and decision consequences.')},
      {id:'systems', name:b('الفهم المؤسسي والمنظومي','Institutional and systems understanding'), weight:15, description:b('فهم الترابط بين العمليات والأفراد والقدرات والموارد والحوكمة.','Understand the connections between operations, people, capabilities, resources and governance.'), evidence:b('خريطة منظومة تتبع انتقال الاحتياج إلى أثر في الجاهزية.','An ecosystem map tracing a requirement to a readiness outcome.')},
      {id:'people', name:b('قيادة الأفراد ونقل الخبرة','People leadership and knowledge transfer'), weight:15, description:b('بناء الثقة وقيادة فرق متنوعة والتعلّم من خبرات الأجيال السابقة.','Build trust, lead diverse teams and learn from the experience of earlier generations.'), evidence:b('ملاحظات سلوكية متعددة المصادر وخطة تطوير فردية.','Multi-source behavioural observations and an individual development plan.')},
      {id:'capability', name:b('القدرات والاستحواذ والموارد','Capabilities, acquisition and resources'), weight:15, description:b('الموازنة بين الحاجة والتكلفة ودورة الحياة والتكامل والاستدامة.','Balance requirements, cost, life cycle, integration and sustainment.'), evidence:b('حالة قرار تقارن بدائل القدرة وتكلفتها الكلية.','A decision case comparing capability options and whole-life cost.')},
      {id:'technology', name:b('التقنية والابتكار المسؤول','Technology and responsible innovation'), weight:10, description:b('تقييم قيمة التقنيات الناشئة وحدودها ومتطلبات البيانات والتكامل.','Evaluate emerging technology value, limitations, data needs and integration.'), evidence:b('ورقة تجربة تربط المشكلة والفرضية ومعايير النجاح.','An experiment brief connecting the problem, hypothesis and success criteria.')},
      {id:'governance', name:b('الحوكمة والسياسات والأخلاقيات','Governance, policy and ethics'), weight:10, description:b('تمييز الصلاحيات والالتزامات والمخاطر وتوثيق القرارات بنزاهة.','Distinguish authorities, obligations and risks, and record decisions with integrity.'), evidence:b('مذكرة تبين صاحب الصلاحية والضوابط وتعارض المصالح.','A memorandum identifying authority, controls and conflicts of interest.')},
      {id:'partnerships', name:b('الشراكات والتواصل الدولي','Partnerships and international engagement'), weight:10, description:b('التواصل عبر الثقافات وفهم التعاون الحكومي والصناعي.','Communicate across cultures and understand government and industrial cooperation.'), evidence:b('موجز تفاوض وخريطة مصالح الشركاء.','A negotiation brief and stakeholder-interest map.')},
      {id:'delivery', name:b('التنفيذ وقياس الأثر','Delivery and impact measurement'), weight:5, description:b('تحويل التعلّم إلى تحسين قابل للتنفيذ والقياس داخل المؤسسة.','Turn learning into an implementable, measurable institutional improvement.'), evidence:b('مشروع أثر بمالك تنفيذي وخط أساس ومراجعات متابعة.','An impact project with an executive owner, baseline and follow-up reviews.')}
    ],
    stations: [
      {id:'uae', code:'AE', country:b('الإمارات','United Arab Emirates'), weeks:3, start:1, end:3, city:b('المنظومة الوطنية','National ecosystem'), title:b('افهم المنظومة التي ستقودها.','Understand the institution you will lead.'), description:b('تأسيس فهم مشترك لوزارة الدفاع ومنظومة تطوير القدرات، وربط الأولويات بالأفراد والموارد والصناعة والجاهزية.','Build a shared understanding of MOD and the capability ecosystem, connecting priorities to people, resources, industry and readiness.'), hosts:[b('مجلس التوازن','Tawazun Council'),b('مجموعة EDGE','EDGE Group'),b('GAL','GAL'),b('معهد الابتكار التكنولوجي TII','Technology Innovation Institute (TII)')], output:b('خريطة المنظومة، خط أساس للجدارات، وتحدٍ مؤسسي معتمد للدراسة.','Ecosystem map, competency baseline and an institutional challenge approved for study.'), note:b('تتضمن المحطة لقاءات مع وظائف الوزارة ذات الصلة، وفق التنسيق الرسمي.','Includes engagement with relevant MOD functions, subject to formal coordination.')},
      {id:'uk', code:'UK', country:b('المملكة المتحدة','United Kingdom'), weeks:6, start:4, end:9, city:b('ساندهيرست • كوسفورد','Sandhurst • Cosford'), title:b('حوّل الفهم إلى ممارسة قيادية.','Turn understanding into leadership practice.'), description:b('قيادة الفرق، التقدير تحت الضغط، الانضباط المهني، وبناء القدرات الفنية وربطها بالجاهزية.','Team leadership, judgement under pressure, professional discipline and the relationship between technical capability and readiness.'), hosts:[b('الأكاديمية العسكرية الملكية ساندهيرست','Royal Military Academy Sandhurst'),b('RAF Cosford','RAF Cosford'),b('أكاديمية الدفاع وجامعة كرانفيلد','Defence Academy and Cranfield University'),b('برامج ومؤسسات وزارة الدفاع البريطانية ذات الصلة','Relevant UK MOD programmes and institutions')], output:b('سجل ملاحظات قيادية، تمرين قرار، ومراجعة جاهزية منظومة.','Leadership observation record, decision exercise and system-readiness review.'), note:b('مسار مخصص مقترح للعسكريين والمدنيين؛ لا يمثل قبولاً في دورة التأهيل العسكري النظامية أو وعداً بمؤهل عسكري.','A proposed tailored pathway for military and civilian personnel; it does not represent admission to a standard commissioning course or a military qualification.')},
      {id:'fr', code:'FR', country:b('فرنسا','France'), weeks:3, start:10, end:12, city:b('باريس • بوردو','Paris • Bordeaux'), title:b('اربط الاستراتيجية بالصناعة.','Connect strategy with industry.'), description:b('الشراكات والاستثمار والهندسة والتكامل ونقل المعرفة، مع فهم العلاقة بين السياسات والقرارات الصناعية ودورة الاستحواذ.','Partnerships, investment, engineering, integration and knowledge transfer, connecting policy to industrial decisions and acquisition.'), hosts:[b('EDGE Europe — باريس','EDGE Europe — Paris'),b('مسار الهندسة والتكامل في بوردو','Engineering and integration track in Bordeaux')], output:b('حالة شراكة أو استحواذ تتضمن التكامل والمخاطر ونقل المعرفة.','A partnership or acquisition case covering integration, risk and knowledge transfer.'), note:b('تبقى EDGE Europe محور المحطة. يحدد نطاق الوصول إلى المواقع والأنشطة بالتنسيق مع الجهة المضيفة.','EDGE Europe remains the station anchor. Site and activity access must be agreed with the host.')},
      {id:'us', code:'US', country:b('الولايات المتحدة','United States'), weeks:4, start:13, end:16, city:b('التعاون الحكومي • الاستحواذ','Government cooperation • Acquisition'), title:b('اختبر القرار. أثبت أثره.','Test the decision. Demonstrate its value.'), description:b('التعاون الحكومي وبرنامج FMS وإدارة الاستحواذ والبرامج والقيادة الاستراتيجية، وصولاً إلى عرض مشروع الأثر أمام لجنة تقييم.','Government cooperation, FMS, acquisition, programme management and strategic leadership, culminating in an assessed impact-project briefing.'), hosts:[b('DSCA وDSCU','DSCA and DSCU'),b('Naval Postgraduate School — مسار إدارة الموارد الدفاعية','Naval Postgraduate School — defence resource management track'),b('مسار التعاون الحكومي والأمني وبرنامج FMS','Government and security cooperation / FMS track'),b('مسار الاستحواذ وإدارة البرامج والعقود','Acquisition, programme management and contracts track'),b('الكليات العسكرية وبرامج القيادة الاستراتيجية','War colleges and strategic-leadership programmes'),b('تطبيق عملي لدى جهة تنفيذية أو مكتب برنامج','Practical attachment with an executive entity or programme office')], output:b('موجز تنفيذي لمشروع الأثر وخطة تطبيق خلال 90 يوماً.','Executive impact-project brief and a 90-day implementation plan.'), note:b('الجهات الأمريكية والمسارات محددة كمقترحات وليست استضافات متفقاً عليها. تُنسّق المدد والأهلية والمواقع لتلائم المحطة ذات الأسابيع الأربعة.','US institutions and tracks are proposed, not agreed hosting arrangements. Duration, eligibility and locations must be coordinated to fit the four-week station.')}
    ],
    weeks: [
      [b('الوزارة كمنظومة','MOD as a system'),b('ارسم علاقة الاستراتيجية والعمليات والموارد والحوكمة.','Map the relationship between strategy, operations, resources and governance.')],
      [b('من الاحتياج إلى القدرة','From need to capability'),b('تتبّع احتياجاً افتراضياً عبر التخطيط والاستحواذ والدعم.','Trace a fictional requirement through planning, acquisition and support.')],
      [b('الابتكار وخط الأساس','Innovation and baseline'),b('حدد تحدي الأثر وسجل خط الأساس وخطة التطوير.','Define the impact challenge and record the baseline and development plan.')],
      [b('القيادة والخدمة','Leadership and service'),b('حلل مسؤولية القائد وسلوك الفريق في موقف مؤسسي.','Analyse a leader’s responsibilities and team behaviour in an institutional situation.')],
      [b('الفرق والثقة','Teams and trust'),b('قد فريقاً متنوعاً واستقبل تغذية راجعة منظمة.','Lead a diverse team and receive structured feedback.')],
      [b('الحكم تحت عدم اليقين','Judgement under uncertainty'),b('قدم خيارات واضحة مع معلومات ناقصة وافتراضات صريحة.','Present clear options using incomplete information and explicit assumptions.')],
      [b('الجاهزية والقدرة الفنية','Readiness and technical capability'),b('اربط التأهيل الفني والسلامة والدعم بمتطلبات الجاهزية.','Connect technical qualification, safety and support to readiness needs.')],
      [b('الموارد ودورة الحياة','Resources and life cycle'),b('قارن بدائل ضمن قيد موارد باستخدام تكلفة دورة الحياة.','Compare alternatives within a resource constraint using life-cycle cost.')],
      [b('مراجعة منتصف المسار','Midpoint review'),b('راجع الأدلة وخطة التطوير وناقش التحدي مع المرشد.','Review evidence and the development plan; discuss the challenge with the mentor.')],
      [b('الشراكات والاستراتيجية الصناعية','Partnerships and industrial strategy'),b('حدد مصالح الشركاء وشروط نجاح العلاقة المؤسسية.','Identify partner interests and the conditions for a successful institutional relationship.')],
      [b('الهندسة والتكامل','Engineering and integration'),b('حلل واجهات المنظومات والاعتماد المتبادل ومخاطر التكامل.','Analyse system interfaces, dependencies and integration risks.')],
      [b('نقل المعرفة والحوكمة','Knowledge transfer and governance'),b('قدم حالة شراكة تميز التعلم ونقل المعرفة عن شراء المنتج.','Present a partnership case distinguishing learning and knowledge transfer from purchasing a product.')],
      [b('التعاون الحكومي وبرنامج FMS','Government cooperation and FMS'),b('تتبّع الأدوار والقرارات في حالة تعليمية للتعاون الحكومي.','Trace roles and decisions in an educational government-cooperation case.')],
      [b('الاستحواذ وإدارة البرامج','Acquisition and programme management'),b('راجع المتطلبات والجدول والتكلفة والمخاطر والحوكمة.','Review requirements, schedule, cost, risk and governance.')],
      [b('الجيوسياسة والسياسات والتقنية','Geopolitics, policy and technology'),b('اختبر أثر تغير خارجي في الخيارات المؤسسية والتقنية.','Test how an external change affects institutional and technology choices.')],
      [b('مشروع الأثر والتقييم الختامي','Impact project and final assessment'),b('دافع عن مشروعك وخطة تطبيقه أمام لجنة، ووثق أهداف المتابعة.','Defend the project and implementation plan before a panel and record follow-up objectives.')]
    ],
    sources: [
      {id:'R1',title:b('توصية القيادة والقدرة في الخدمة العامة','Recommendation on Public Service Leadership and Capability'),publisher:'OECD',url:'https://legalinstruments.oecd.org/public/doc/641/641.en.pdf',use:b('مرجع لتطوير القيادة والتعلم والثقافة المؤسسية؛ ليس اعتماداً لبرنامج سمت.','Reference for leadership development, learning and institutional culture; not SAMT accreditation.')},
      {id:'R2',title:b('تصميم التدريب القيادي وتنفيذه — تحليل تلوي','Leadership training design, delivery, and implementation: A meta-analysis'),publisher:'Lacerenza et al. · Journal of Applied Psychology · 2017',url:'https://pubmed.ncbi.nlm.nih.gov/28749153/',use:b('يسند الجمع بين الممارسة والتغذية الراجعة وتقييم الاحتياجات. لا يثبت فعالية سمت قبل تجربته.','Supports practice, feedback and needs assessment. It does not establish SAMT’s effectiveness before a pilot.')},
      {id:'R3',title:b('التدريب في ساندهيرست','Officer training at RMA Sandhurst'),publisher:'British Army',url:'https://www.army.mod.uk/support-and-training/our-schools-and-colleges/rma-sandhurst/officer-training/',use:b('الاختصاص المؤسسي؛ المسار المخصص ومشاركة المدنيين يتطلبان اتفاقاً مستقلاً.','Institutional remit; a tailored pathway and civilian participation require a separate agreement.')},
      {id:'R4',title:b('قاعدة RAF Cosford','RAF Cosford'),publisher:'Royal Air Force',url:'https://www.raf.mod.uk/our-organisation/stations/raf-cosford/',use:b('دور القاعدة في التدريب الفني؛ لا يثبت توافر مقاعد لسمت.','The station’s technical-training role; does not establish SAMT seat availability.')},
      {id:'R5',title:b('إطلاق EDGE Europe','Launch of EDGE Europe'),publisher:'EDGE · 11 June 2026',url:'https://edgegroup.ae/news/launch-edge-europe-edge-heralds-new-model-european-defence',use:b('أساس علني لمساري باريس وبوردو؛ الاستضافة لم يتم الاتفاق عليها.','Public basis for Paris and Bordeaux tracks; hosting has not been agreed.')},
      {id:'R6',title:b('دليل إدارة المساعدة الأمنية','Security Assistance Management Manual'),publisher:'DSCA',url:'https://samm.dsca.mil/listing/chapters',use:b('مرجع تعليمي لأدوار وإجراءات التعاون الأمني وبرنامج FMS.','Educational reference for security-cooperation and FMS roles and processes.')},
      {id:'R7',title:b('عن معهد الابتكار التكنولوجي','About Technology Innovation Institute'),publisher:'TII',url:'https://www.tii.ae/about-us',use:b('السياق البحثي والتقني للمحطة الوطنية.','Research and technology context for the national station.')},
      {id:'R8',title:b('خدمات الدعم والاستدامة','Sustainment services'),publisher:'GAL',url:'https://www.gal.ae/products-services',use:b('سياق الدعم الفني والصيانة وإدامة القدرة.','Context for technical support, maintenance and capability sustainment.')},
      {id:'R9',title:b('معنى السمت في المعجم الوسيط','Meaning of samt in Al Muʿjam Al Wasit'),publisher:'مجمع اللغة العربية بالقاهرة · Academy of the Arabic Language in Cairo',url:'https://www.arabicacademy.gov.eg/ar/محرك-البحث/السمت',use:b('المعنى المعجمي للطريق والهيئة؛ تطبيقه على القيادة تفسير لهوية المبادرة.','Lexical meanings of path and bearing; the leadership application is the initiative’s interpretation.')},
      {id:'R10',title:b('مركز الإدارة والقيادة الدفاعية','Centre for Defence Management and Leadership'),publisher:'Cranfield University',url:'https://www.cranfield.ac.uk/centres/centre-for-defence-management-and-leadership',use:b('مرجع لاختصاص التعليم القيادي والإداري الدفاعي، دون افتراض القبول أو المدة.','Reference for defence leadership and management education, without assuming admission or duration.')},
      {id:'R11',title:b('جامعة التعاون الأمني الدفاعي','Defense Security Cooperation University'),publisher:'DSCU',url:'https://www.dscu.edu/',use:b('اختصاص تعليم التعاون الأمني؛ يحتاج المسار المقترح إلى تنسيق رسمي.','Security-cooperation education remit; the proposed pathway requires formal coordination.')},
      {id:'R12',title:b('تعليم الاستراتيجية وإدارة الموارد الدفاعية','Strategy and defence resource management education'),publisher:'Naval Postgraduate School · 2021',url:'https://nps.edu/-/annual-course-builds-strategy-resource-management-skills-for-us-int-l-leaders',use:b('مثال تاريخي على التعليم للعسكريين والمدنيين؛ ليس دليلاً على إتاحة دورة حالية أو ملاءمة أهلية جميع المرشحين.','Historical example of military and civilian education; not evidence of a currently available course or eligibility of all candidates.')}
    ],
    proposal: [
      {id:'decision',title:b('القرار المطلوب','Decision requested'),paragraphs:[
        b('أقترح تبنّي مبادرة سَمْت من حيث المبدأ، وتكليف جهة راعية داخل وزارة الدفاع بتطوير تصميمها التنفيذي وإتمام دراسة الجدوى والتنسيق مع الجهات المضيفة، تمهيداً لاتخاذ قرار مستقل بشأن إطلاق دورة تجريبية.','I propose that the Ministry of Defence endorse SAMT in principle and appoint an institutional sponsor to develop the delivery design, complete feasibility work and coordinate with proposed hosts, before a separate decision to launch a pilot.'),
        b('المبادرة مقدمة من أحمد يونس يوسف الحمادي. وهي مقترح يسعى إلى تبنّي الوزارة، ولا تمثل برنامجاً معتمداً أو شراكات قائمة. لا يترتب على الموافقة المبدئية التزام مالي أو إعلان فتح باب الترشيح الفعلي.','The initiative is proposed by Ahmed Younis Yousif Alhammadi. It seeks MOD adoption and does not represent an approved programme or existing partnerships. In-principle endorsement would not itself create a financial commitment or open real nominations.'),
        b('تتضمن حزمة القرار التصميم المقترح، الحوكمة، الاختيار، رحلة التعلم، التقييم، متابعة الأثر، نموذج التكاليف وسجل المخاطر، إضافة إلى تجربة رقمية ببيانات افتراضية.','The decision package includes proposed programme design, governance, selection, learning, assessment, impact follow-up, a cost model and a risk register, alongside a digital demonstration using fictional data.')
      ]},
      {id:'need',title:b('الحاجة والقيمة المؤسسية','Institutional need and value'),paragraphs:[
        b('تعالج المبادرة فجوة يحددها صاحب المقترح بين الخبرة المتراكمة لدى الجيل القيادي القائم والموهبة الواعدة لدى الجيل التالي، بالتزامن مع تغير التقنية والصناعة والجيوسياسة والسياسات. ينبغي التحقق من حجم هذه الفجوة بمقابلات وبيانات تطوير الكوادر خلال مرحلة الجدوى.','The initiative addresses a gap identified by its proposer between the accumulated experience of established leaders and the promise of the next generation, alongside technological, industrial, geopolitical and policy change. Its scale should be validated through interviews and workforce-development evidence during feasibility work.'),
        b('القيمة المقصودة هي إعداد عسكريين ومدنيين ذوي إمكانات استثنائية لفهم المنظومة المؤسسية واتخاذ قرارات أفضل والعمل عبر حدود الوظائف. يشمل ذلك الاستراتيجية والعمليات والموارد البشرية والقدرات والاستحواذ والمالية والصناعة والدعم والحوكمة.','The intended value is to prepare exceptional military and civilian personnel to understand the institutional ecosystem, make better decisions and work across functions. This includes strategy, operations, people, capabilities, acquisition, finance, industry, support and governance.'),
        b('يُستفاد من مراجع OECD وأبحاث التدريب القيادي في تصميم الممارسة والتغذية الراجعة ونقل التعلم إلى العمل. هذه مبررات تصميمية وليست دليلاً على تحقق أثر سمت؛ إثبات ذلك يتطلب دورة تجريبية وقياساً لاحقاً. [R1، R2]','OECD guidance and leadership-training research inform the use of practice, feedback and transfer to work. These are design rationales, not evidence that SAMT has delivered impact; that requires a pilot and follow-up measurement. [R1, R2]')
      ]},
      {id:'charter',title:b('ميثاق البرنامج وحدوده','Programme charter and boundaries'),paragraphs:[
        b('الفئة المستهدفة هي عسكريون ومدنيون من وزارة الدفاع حصراً، من المراحل المبكرة والمتوسطة مهنياً، ويكون التميز والإمكانات القيادية محور الاختيار. الحد الأقصى 20 مشاركاً في الدورة، ويحدد الحجم النهائي وفق قدرة الاستضافة والإشراف والتمويل.','Participants are exclusively MOD military and civilian personnel at early and middle career stages, selected for exceptional ability and leadership potential. Each cycle is capped at 20; the final size depends on host capacity, supervision and funding.'),
        b('المدة الملزمة 16 أسبوعاً متتالياً بدوام كامل في الإمارات والمملكة المتحدة وفرنسا والولايات المتحدة. التوزيع المرجعي 3 و6 و3 و4 أسابيع على التوالي. تُدمج الانتقالات والمراجعات ضمن هذه المدة، وتحتاج ساعات الاتصال وأيام السفر إلى جدول تنفيذي معتمد.','The fixed duration is 16 consecutive full-time weeks across the UAE, UK, France and US. The reference allocation is 3, 6, 3 and 4 weeks respectively. Transitions and reviews sit within this period; contact hours and travel days require an approved delivery schedule.'),
        b('تبقى الجهات والمسارات الموضحة في ملحق المحطات ثابتة في التصميم، مع إمكان إضافة جهات تخدم نواتج التعلم. كل استضافة أو تخصيص مقاعد أو استخدام موقع يتطلب اتفاقاً رسمياً. وتبقى متابعة 12 شهراً بعد العودة أساساً مقترحاً قابلاً للتفصيل.','Hosts and tracks listed in the stations appendix remain design anchors, with additions allowed where they serve learning outcomes. Every hosting arrangement, seat allocation and site access requires formal agreement. Twelve months of follow-up remains the proposed baseline.'),
        b('لا تمنح المشاركة رتبة أو ترقية أو أهلية تلقائية لتولي القيادة. ولا تمنح المبادرة شهادة أكاديمية أو مهنية معتمدة ما لم يُبرم اتفاق صريح مع جهة مخولة.','Participation does not confer rank, promotion or automatic eligibility for command. No accredited academic or professional award is claimed without an explicit agreement with an authorised awarding body.')
      ]},
      {id:'selection',title:b('الترشيح والاختيار','Nomination and selection'),paragraphs:[
        b('تبدأ العملية بترشيح مؤسسي مدعوم بأدلة أداء واستعداد للتفرغ وخطاب يوضح الدافع. تراجع الأهلية أولاً، ثم تُجرى دراسة حالة وتمرين جماعي ومقابلة منظمة، وتنتهي بمراجعة لجنة متعددة التخصصات.','The process begins with institutional nomination supported by performance evidence, full-time availability and a motivation statement. Eligibility is checked first, followed by a case exercise, group exercise and structured interview, then a multidisciplinary panel review.'),
        b('مقترح المفاضلة هو 30% للتحليل والتقدير، 25% للتعلم وفهم المنظومة، 20% لقيادة الفريق، 15% للدافع والوعي الذاتي، و10% للتواصل. السلوك المهني والنزاهة شرط مستقل. تُعاير المعايير خلال التجربة قبل اعتماد أي حد للنجاح.','The proposed selection weighting is 30% analysis and judgement, 25% learning and systems understanding, 20% team leadership, 15% motivation and self-awareness, and 10% communication. Professional conduct and integrity are a separate condition. Criteria should be calibrated in the pilot before any pass threshold is adopted.'),
        b('يوثق مقيمان على الأقل الأدلة، وتراجع اللجنة الحالات المتباينة مع الإفصاح عن تعارض المصالح. تكون القرارات مسببة وقابلة للمراجعة، ويستخدم الفرز العددي لمساندة الحكم البشري. لا تُفترض حدود عمر أو رتبة أو سنوات خدمة غير مقررة من الوزارة.','At least two assessors document evidence; the panel reviews divergent cases and declares conflicts of interest. Decisions are reasoned and reviewable, with numerical scoring supporting human judgement. No unapproved age, rank or service-length limits are assumed.')
      ]},
      {id:'learning',title:b('التعلم التطبيقي ونقل الخبرة','Applied learning and knowledge transfer'),paragraphs:[
        b('يتبع الجميع نواة مشتركة لفهم منظومة الوزارة، مع تكليفات تتناسب مع الخبرة والوظيفة. يربط كل أسبوع بين سؤال مؤسسي، لقاء أو حالة تطبيقية، مخرج مكتوب، وتغذية راجعة. يدوّن المشارك ما تعلمه وكيف سيستخدمه وما يحتاج إلى التحقق منه.','All fellows follow a shared core in MOD ecosystem understanding, with assignments adapted to experience and function. Each week connects an institutional question, a host engagement or applied case, a written output and feedback. Fellows record what they learned, how it may be used and what still needs validation.'),
        b('يُقرن كل مشارك بمرشد ذي خبرة، وتضم فرق العمل عسكريين ومدنيين وخبرات متفاوتة. تُستخدم جلسات خبرة منظمة، ومراجعات بعد النشاط، ومناقشات بين الأجيال لحفظ المعرفة الضمنية وإعادة اختبارها في سياق جديد.','Each fellow is paired with an experienced mentor. Project teams mix military and civilian perspectives and experience levels. Structured experience discussions, after-action reviews and intergenerational dialogue preserve tacit knowledge and test its relevance in a new context.'),
        b('يبدأ مشروع الأثر في المحطة الوطنية وينمو عبر المحطات الأربع. تشمل أمثلته التعليمية تحسين تدفق القرار أو تبادل المعرفة أو كفاءة عملية دعم، ويختار مالك مؤسسي التحدي وخط الأساس ونطاق البيانات المسموح به.','The impact project starts in the UAE and develops across all four stations. Educational examples include improving decision flow, knowledge exchange or a support process. An institutional owner approves the challenge, baseline and permitted data scope.')
      ]},
      {id:'assessment',title:b('التقييم والتخرج','Assessment and completion'),paragraphs:[
        b('يُقاس التقدم عبر ثمانية مجالات موضحة في إطار الجدارات. لكل مجال شواهد سلوكية ومخرجات، ويستخدم سلم من 1 إلى 5 من الفهم الأساسي إلى التطبيق المستقل والتفسير المقنع للبدائل. الأوزان المقترحة مجموعها 100% ولا تمثل معياراً معتمداً.','Progress is assessed across eight competency domains. Each has behavioural evidence and outputs, using a 1–5 scale from basic understanding to independent application and reasoned explanation of alternatives. Proposed weights total 100% and are not an approved standard.'),
        b('يجمع التقييم خط الأساس، أدلة الأسبوع، ملاحظات المضيف والمرشد، مراجعة منتصف البرنامج، وتمرين القرار والعرض الختامي. الفرق بين قياسين على سلم ترتيبي وصف للتقدم، ولا يكفي وحده لإثبات انتقال الأثر إلى العمل.','Assessment combines baseline, weekly evidence, host and mentor observations, midpoint review, a decision exercise and final briefing. A change on an ordinal rating scale describes progress; it does not alone prove transfer to work.'),
        b('توصي اللجنة بالتخرج عند اكتمال الأدلة الأساسية ومشروع الأثر وخطة التطبيق والسلوك المهني المطلوب. تُوثق الفجوات وخطة المعالجة عند الحاجة، ولا تستخدم الدرجة الإجمالية وحدها لتجاوز نقص جوهري.','The panel recommends completion when essential evidence, the impact project, implementation plan and professional-conduct requirements are met. Gaps and remediation are documented when needed; an aggregate score cannot by itself override a material deficiency.')
      ]},
      {id:'governance',title:b('الحوكمة والمسؤوليات','Governance and responsibilities'),paragraphs:[
        b('يُقترح راعٍ مؤسسي مخول يعتمد الاتجاه وقرارات البوابات، ولجنة توجيه تضم التطوير والموارد البشرية والعمليات والمالية والشؤون القانونية والتعاون الدولي. تدير وحدة البرنامج التنفيذ والسجل والمواعيد، وتملك لجنة تقييم مستقلة نسبياً قرارات الاختيار والتخرج.','An authorised institutional sponsor would own direction and gate decisions, supported by a steering committee covering development, HR, operations, finance, legal affairs and international cooperation. A programme office would manage delivery, records and scheduling; a sufficiently independent assessment panel would own selection and completion decisions.'),
        b('يعين كل مشروع أثر مالك منفعة داخل جهة العمل. وتكون للمالية مسؤولية التحقق من التكلفة، وللجهة المخولة مسؤولية اعتماد الالتزام، وللمضيف مسؤولية اعتماد محتواه وتقييمه. تُحدد صلاحيات حماية المعلومات والاستضافة الرقمية وفق متطلبات الوزارة قبل أي تشغيل حقيقي.','Each impact project has a benefits owner in the home organisation. Finance verifies cost; the authorised authority approves commitments; hosts approve their content and assessment. Information protection and digital-hosting responsibilities must be set under MOD requirements before real operation.')
      ]},
      {id:'gates',title:b('بوابات الاعتماد والتنفيذ','Approval and delivery gates'),rows:[
        [b('البوابة','Gate'),b('المسؤول المقترح','Proposed owner'),b('الدليل المطلوب','Required evidence')],
        [b('تبنّي المبدأ','In-principle endorsement'),b('الراعي المخول','Authorised sponsor'),b('قصد واضح ونطاق ثابت وتكليف فريق التصميم.','Clear purpose, fixed scope and a commissioned design team.')],
        [b('الجدوى والتصميم','Feasibility and design'),b('لجنة التوجيه ووحدة البرنامج','Steering committee and programme office'),b('احتياج مثبت، نتائج تعلم، جدول 16 أسبوعاً، إمكان استضافة العسكريين والمدنيين.','Validated need, learning outcomes, 16-week timetable and host feasibility for military and civilian personnel.')],
        [b('جاهزية الإطلاق','Launch readiness'),b('الراعي والمالية والجهات المختصة','Sponsor, finance and relevant authorities'),b('اتفاقات مضيفين، تكلفة موثقة وممولة، معايير اختيار، خطة سفر ومعلومات وتقييم.','Host agreements, evidenced and funded cost, selection criteria, and travel, information and assessment plans.')],
        [b('تنفيذ التجربة','Pilot delivery'),b('مدير البرنامج والمضيفون','Programme director and hosts'),b('مراجعات أسبوعية، قرارات بوابات المحطات، معالجة حالات التعثر.','Weekly reviews, station gate decisions and remediation for participants who need support.')],
        [b('التبني المستدام','Sustained adoption'),b('الراعي ومالكو المنافع','Sponsor and benefits owners'),b('نتائج تجربة ومراجعات 90 و180 و365 يوماً وقرار استمرار أو تعديل.','Pilot results, 90-, 180- and 365-day reviews and a continue-or-adapt decision.')]
      ]},
      {id:'impact',title:b('متابعة الأثر بعد البرنامج','Post-programme impact'),paragraphs:[
        b('المتابعة المقترحة 12 شهراً وتشمل ثماني نقاط إرشاد في الأشهر 1 و2 و3 و4 و6 و8 و10 و12. توثق أهداف التطوير وتطبيق المشروع وتحديات العودة إلى العمل وملاحظات المدير المباشر.','The proposed 12-month follow-up includes eight mentoring touchpoints in months 1, 2, 3, 4, 6, 8, 10 and 12. Records cover development objectives, project implementation, return-to-work challenges and line-manager feedback.'),
        b('تقاس جودة التنفيذ باكتمال الأدلة والتغذية الراجعة، ويقاس التعلم بمهام أداء قبل البرنامج وبعده، ويقاس الانتقال إلى العمل بأمثلة موثقة من المدير والمرشد، وتقاس المنفعة بنتيجة المشروع مقارنة بخط أساس متفق عليه.','Delivery quality is measured through evidence and feedback completeness; learning through before-and-after performance tasks; transfer through documented manager and mentor examples; benefits through project outcomes against an agreed baseline.'),
        b('تُعرض المقامات وحجم العينة وحالات عدم الاستجابة. أهداف مثل تحسن الجاهزية أو تقليل زمن إجراء تحتاج إلى تعريف ومالك بيانات؛ لا تُعرض كوعود أو نتائج محققة. وعند الإمكان تستخدم مجموعة مقارنة مناسبة مع مراعاة اختلاف الوظائف.','Report denominators, sample size and non-response. Readiness improvement or process-time reduction requires a definition and data owner; neither is presented as a promise or achieved result. Where practical, use a suitable comparison group while accounting for differences in roles.')
      ]},
      {id:'cost',title:b('نموذج التكلفة والتمويل','Cost and funding model'),paragraphs:[
        b('تحسب تكلفة الدورة من نفقات تأسيس ثابتة ورسوم تدريب وسفر وإقامة ومعيشة وتأمين ودعم لكل مشارك، ثم احتياطي معتمد. تشمل التكلفة الاقتصادية وقت التفرغ والإحلال والفرصة البديلة حتى إن لم تكن دفعات إضافية.','Cycle cost combines fixed setup, per-participant training, travel, accommodation, subsistence, insurance and support, plus an approved contingency. Economic cost also includes release time, cover and opportunity cost even where these are not additional payments.'),
        b('يعرض الموقع حاسبة تخطيط بمدخلات افتراضية قابلة للتعديل. افتراضها 91 يوماً خارج الدولة ضمن توزيع 3 و6 و3 و4 أسابيع. عدد ليالي الإقامة الفعلي وأيام السفر والرسوم والضرائب والتأمين تحدد بعروض وترتيبات موثقة. لا تمثل الأرقام تسعيراً من المضيفين أو طلب اعتماد ميزانية.','The website provides a planning calculator with editable illustrative inputs. It assumes 91 days abroad within the 3/6/3/4-week allocation. Actual nights, travel days, fees, taxes and insurance require documented quotations and arrangements. Figures are neither host quotations nor a budget approval request.'),
        b('قبل قرار الإطلاق، تعرض المالية ثلاث حالات لحجم الدفعة حتى 20 مشاركاً، مع حساسية أسعار الصرف والإلغاء والتأخير ونطاق يشمل جميع البنود. يحدد السقف المالي بعد التحقق ولا يستنتج من بيانات العرض.','Before launch, finance should present three cohort-size cases up to 20 participants, sensitivity to exchange rates, cancellation and delay, and a fully scoped cost estimate. The budget ceiling is set after verification, not inferred from demonstration data.')
      ]},
      {id:'risks',title:b('المخاطر ومعالجتها','Risks and treatment'),rows:[
        [b('الخطر','Risk'),b('المعالجة','Treatment'),b('المالك المقترح','Proposed owner')],
        [b('تعذر استضافة أو أهلية مدنية','Host unavailability or civilian eligibility'),b('اتفاق مكتوب بمسار مخصص؛ لا يُستبدل المضيف الثابت دون قرار صاحب المبادرة والوزارة.','Written agreement for a tailored pathway; a fixed host is not replaced without proposer and MOD decision.'),b('التعاون الدولي','International cooperation')],
        [b('اضطراب السفر أو الجيوسياسة','Travel or geopolitical disruption'),b('مراجعة الجاهزية قبل الإطلاق وخطة استجابة تحافظ على القيود أو تعيد القرار للراعي.','Pre-launch readiness review and response plan that respects constraints or returns the decision to the sponsor.'),b('مدير البرنامج','Programme director')],
        [b('تحيز الاختيار أو التقييم','Selection or assessment bias'),b('معايير سلوكية ومقيمان ومعايرة وتعارض مصالح ومراجعة قرار.','Behavioural criteria, two assessors, calibration, conflict declarations and decision review.'),b('لجنة التقييم','Assessment panel')],
        [b('ضعف انتقال التعلم إلى العمل','Weak transfer to work'),b('مالك منفعة ووقت مخصص للتطبيق وإرشاد ومتابعة 12 شهراً.','Benefits owner, protected application time, mentoring and 12-month follow-up.'),b('المدير المباشر','Line manager')],
        [b('عدم ضبط التكلفة','Cost uncertainty'),b('عروض موثقة ونطاق كامل واحتياطي ومراجعة تغيرات.','Documented quotations, complete scope, contingency and change review.'),b('المالية','Finance')],
        [b('إدخال معلومات حقيقية في العرض','Real information entered into the demo'),b('بيانات افتراضية فقط؛ لا ربط بأنظمة الوزارة ولا استقبال وثائق أو معرفات فعلية.','Fictional data only; no MOD-system connection or collection of real documents or identifiers.'),b('مالك المنصة','Platform owner')]
      ]},
      {id:'digital',title:b('المنظومة الرقمية وخارطة الانتقال','Digital ecosystem and transition'),paragraphs:[
        b('الإصدار الحالي عرض تفاعلي للترشيح والاختيار والتعلم والمتابعة والتقييم. جميع الملفات والأرقام والأسماء البديلة افتراضية. تحفظ تغييرات العرض في متصفح المستخدم فقط، ويمكن إعادة ضبطها؛ لا توجد حسابات فعلية أو رسائل أو إرسال إلى الوزارة.','This release demonstrates nomination, selection, learning, monitoring and assessment. Records, figures and aliases are fictional. Demo changes are saved only in the user’s browser and can be reset; there are no real accounts, messages or submissions to MOD.'),
        b('قبل التشغيل الحقيقي يلزم اعتماد نموذج الأدوار والصلاحيات، والهوية المؤسسية، ومكان استضافة البيانات، والاحتفاظ والحذف، وسجل تدقيق على الخادم، وخطة الاستجابة والدعم، والتكاملات التي تختارها الوزارة. هذه متطلبات انتقال وليست قدرات أمنية متحققة في العرض.','Real operation requires an approved role and permissions model, institutional identity, data hosting, retention and deletion, server-side audit, incident response and support, and integrations selected by MOD. These are transition requirements, not security capabilities established by this demonstration.'),
        b('تبدأ خارطة التنفيذ بتصميم تفصيلي وتحقق من المضيفين، ثم إعداد التجربة ومعايرة أدوات التقييم، ثم تنفيذ الدورة ذات الأسابيع الستة عشر، ثم متابعة الأثر ومراجعة التوسع. المواعيد الفعلية تُبنى على الموافقات والجاهزية ولا تُعلن كتاريخ إطلاق مؤكد.','Delivery begins with detailed design and host validation, followed by pilot preparation and assessment calibration, the 16-week cycle, then impact follow-up and a scale decision. Actual dates depend on approvals and readiness; no confirmed launch date is claimed.')
      ]}
    ]
  };
})();
